# Generated by Django 5.0.6 on 2024-05-25 18:44

import cash_out.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальна довжина 100 символів', max_length=100, verbose_name='Причина скидання:')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
            ],
        ),
        migrations.CreateModel(
            name='SenderMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальна довжина 100 символів', max_length=100, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, help_text="Максимальна довжина 100 символів. Не обов'язкове.", max_length=100, null=True, verbose_name='Фамілія')),
                ('other_info', models.CharField(blank=True, help_text="Додайте примітку до платника. Не обов'язкове.", max_length=100, null=True, verbose_name='Примітка')),
                ('date_time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
            ],
        ),
        migrations.CreateModel(
            name='OutcomingMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_oper', models.CharField(default='Outcoming', help_text=cash_out.models.help_txt_money, max_length=30, verbose_name='Тип операції')),
                ('count_money', models.SmallIntegerField(verbose_name='Сумма.')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Час створення запису')),
                ('rsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_out', to='cash_out.reasons')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_oper', models.CharField(default='Incom', help_text=cash_out.models.help_txt_money, max_length=30, verbose_name='Тип операції')),
                ('count_money', models.SmallIntegerField(verbose_name='К-ть грн(одна людина).')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Час створення запису')),
                ('rsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_in', to='cash_out.reasons')),
                ('who_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who', to='cash_out.sendermoney')),
            ],
        ),
    ]
