# Generated by Django 5.0.6 on 2024-05-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_out', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingmoney',
            options={'managed': True, 'verbose_name': 'Приход грошей', 'verbose_name_plural': 'Приход грошей'},
        ),
        migrations.AlterModelOptions(
            name='outcomingmoney',
            options={'managed': True, 'verbose_name': 'Витрата грошей', 'verbose_name_plural': 'Витрата грошей'},
        ),
        migrations.AlterModelOptions(
            name='reasons',
            options={'managed': True, 'verbose_name': 'На що скидались', 'verbose_name_plural': 'На що скидались'},
        ),
        migrations.AlterModelOptions(
            name='sendermoney',
            options={'managed': True, 'verbose_name': 'Відправник $$$', 'verbose_name_plural': 'Відправники $$$'},
        ),
        migrations.AddIndex(
            model_name='sendermoney',
            index=models.Index(fields=['id', 'date_time_create'], name='cash_out_se_id_56a1a4_idx'),
        ),
    ]
